### ISSUE TITLE
pip installation won't load (no gexml)

### ISSUE THREAD

**Issue by bradh** [ampledata/pycot#3]
```
bradh@marginata:~/MAVProxy$ pip install pycot
Collecting pycot
  Downloading pycot-1.0.0.tar.gz
Building wheels for collected packages: pycot
  Running setup.py bdist_wheel for pycot ... done
  Stored in directory: /home/bradh/.cache/pip/wheels/4d/a0/f4/b3dbef56016f1d99e6715f77113e9ae31d1437c99c31ca9dd8
Successfully built pycot
Installing collected packages: pycot
Successfully installed pycot-1.0.0
bradh@marginata:~/MAVProxy$ python 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bradh/.local/lib/python2.7/site-packages/pycot/__init__.py", line 24, in <module>
    from .classes import Event, Point, Detail  # EventType, AtomEventType, DataEventType  # NOQA
  File "/home/bradh/.local/lib/python2.7/site-packages/pycot/classes.py", line 8, in <module>
    import gexml
ImportError: No module named gexml
```

Looks like gexml isn't in pip.

**Comment by bradh** [comment]
Also `nosetests` target won't pass for me without the aprs module, which isn't a defined dependency.
